from . import photo_views
from . import chat_views
from . import notice_views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views
from . import workforce_views as workforce
from .forms import LoginForm

app_name = 'web'
urlpatterns = [
    path('notices/', notice_views.notices, name='notices'),
    path('notices/new/', notice_views.notice_new, name='notice-new'),
    path('notices/<int:pk>/delete/', notice_views.notice_delete, name='notice-delete'),
    path('chat/', chat_views.chat_home, name='chat-home'),
    path('chat/channels/new/', chat_views.chat_channel_new, name='chat-channel-new'),
    path('chat/<int:channel_id>/', chat_views.chat_channel, name='chat-channel'),
    path('chat/<int:channel_id>/send/', chat_views.chat_send, name='chat-send'),
    path('attendance/photos/', photo_views.queue, name='photo-attendance'),
    path('attendance/photos/<int:pk>/image/', photo_views.photo, name='attendance-photo-image'),
    path('attendance/photos/<int:pk>/review/', photo_views.review, name='attendance-photo-review'),
    path('caller-sessions/', views.caller_sessions, name='caller-sessions'),
    path('leads/quick-entry/', views.quick_leads, name='lead-quick-entry'),
    path('register/', workforce.register, name='register'),
    path('employee/', workforce.employee_home, name='employee-home'),
    path('employees/', workforce.employees, name='employees'),
    path('people/', workforce.people_overview, name='people-overview'),
    path('finance/', workforce.finance_overview, name='finance-overview'),
    path('employees/<int:pk>/', workforce.employee_edit, name='employee-edit'),
    path('leave/', workforce.leaves, name='leaves'),
    path('leave/apply/', workforce.leave_apply, name='leave-apply'),
    path('leave/<int:pk>/action/', workforce.leave_action, name='leave-action'),
    path('attendance/', workforce.attendance, name='attendance'),
    path('attendance/action/', workforce.attendance_action, name='attendance-action'),
    path('holidays/', workforce.holidays, name='holidays'),
    path('holidays/new/', workforce.holiday_new, name='holiday-new'),
    path('holidays/<int:pk>/', workforce.holiday_new, name='holiday-edit'),
    path('holidays/<int:pk>/remove/', workforce.holiday_remove, name='holiday-remove'),
    path('projects/', workforce.projects, name='projects'),
    path('projects/new/', workforce.project_new, name='project-new'),
    path('projects/<int:pk>/status/', workforce.project_update, name='project-update'),
    path('reports/', workforce.reports, name='reports'),
    path('reports/new/', workforce.report_edit, name='report-new'),
    path('reports/<int:pk>/', workforce.report_edit, name='report-edit'),
    path('feedback/', workforce.feedback, name='feedback'),
    path('expenses/', workforce.expenses, name='expenses'),
    path('expenses/new/', workforce.expense_new, name='expense-new'),
    path('expenses/<int:pk>/void/', workforce.expense_void, name='expense-void'),
    path('payroll/', workforce.payroll, name='payroll'),
    path('payroll/new/', workforce.payroll_new, name='payroll-new'),
    path('payroll/<int:pk>/edit/', workforce.payroll_new, name='payroll-edit'),
    path('payroll/<int:pk>/query/', workforce.payroll_query, name='payroll-query'),
    path('payroll/queries/<int:pk>/resolve/', workforce.payroll_resolve, name='payroll-resolve'),
    path('activity/', workforce.activity_log, name='activity-log'),
    path('leads/<int:pk>/collaboration/', workforce.lead_collaboration, name='lead-collaboration'),
    path('consultations/', workforce.consultations, name='consultations'),
    path('leads/distribute/', workforce.distribute, name='lead-distribute'),
    path('consultations/<int:pk>/resolve/', workforce.consult_resolve, name='consult-resolve'),
    path('customers/', workforce.customers, name='customers'),
    path('customers/new/', workforce.customer_new, name='customer-new'),
    path('invoices/', workforce.invoices, name='invoices'),
    path('invoices/new/', workforce.invoice_new, name='invoice-new'),
    path('invoices/<int:pk>/', workforce.invoice_detail, name='invoice-detail'),
    path('login/', LoginView.as_view(template_name='web/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('leads/', views.leads, name='leads'),
    path('leads/new/', views.lead_create, name='lead-create'),
    path('leads/import/', views.lead_import, name='lead-import'),
    path('leads/assign/', views.lead_assign, name='lead-assign'),
    path('leads/<int:pk>/', views.lead_detail, name='lead-detail'),
    path('calls/', views.calls, name='calls'),
    path('follow-ups/', views.followups, name='followups'),
    path('follow-ups/<int:pk>/complete/', views.followup_complete, name='followup-complete'),
    path('team/', views.team, name='team'),
]
