# Generated by Django 6.1.1 on 2026-09-16 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0003_lead_import_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('LEAD_CREATED', 'Lead created'), ('STATUS_CHANGED', 'Status changed'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('CALL_LOGGED', 'Call logged'), ('FOLLOWUP_SCHEDULED', 'Follow-up scheduled'), ('FOLLOWUP_COMPLETED', 'Follow-up completed'), ('FOLLOWUP_CANCELLED', 'Follow-up cancelled'), ('LOGGED_IN', 'Logged in'), ('LOGGED_OUT', 'Logged out')], db_index=True, max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
