# Generated by Django 6.1.1 on 2026-10-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activitylog_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='verb',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead created'), ('STATUS_CHANGED', 'Status changed'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('CALL_LOGGED', 'Call logged'), ('FOLLOWUP_SCHEDULED', 'Follow-up scheduled'), ('FOLLOWUP_COMPLETED', 'Follow-up completed'), ('FOLLOWUP_CANCELLED', 'Follow-up cancelled'), ('LOGGED_IN', 'Logged in'), ('LOGGED_OUT', 'Logged out'), ('WHATSAPP_INITIATED', 'WhatsApp initiated'), ('COUNSELOR_FORWARDED', 'Forwarded to counselor'), ('COUNSELOR_REASSIGNED', 'Counselor changed'), ('ADMISSION_REQUESTED', 'Admission requested')], db_index=True, max_length=30),
        ),
    ]
