# Generated by Django 6.1.1 on 2026-09-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_user_updated_at_alter_user_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CALLER', 'Caller'), ('IT', 'IT'), ('VIDEO_EDITOR', 'Video Editor'), ('ACCOUNTANT', 'Accountant'), ('EMPLOYEE', 'Employee')], default='CALLER', max_length=30),
        ),
    ]
