# Generated by Django 6.1.1 on 2026-09-14 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_callersession'),
        ('web', '0003_attendancephotorequest_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='callersession',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='web.attendance'),
        ),
        migrations.AddField(
            model_name='callersession',
            name='end_reason',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='callersession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callersession',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.attendancephotorequest'),
        ),
        migrations.AddField(
            model_name='callersession',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_pending',
            field=models.BooleanField(default=False),
        ),
    ]
