# Generated by Django 6.1.1 on 2026-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_callersession_attendance_callersession_end_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callersession',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callersession',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
