# Generated by Django 6.1.1 on 2026-09-28 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_callersession_ip_address_callersession_latitude_and_more'),
        ('leads', '0008_service_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_mappings', to='leads.service')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employees', through='accounts.EmployeeService', to='leads.service'),
        ),
        migrations.AddConstraint(
            model_name='employeeservice',
            constraint=models.UniqueConstraint(fields=('employee', 'service'), name='unique_employee_service'),
        ),
    ]
