# Generated by Django 6.1.1 on 2026-09-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pushdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushReceipt',
            fields=[
                ('ticket_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device_last_seen', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounts.pushdevice')),
            ],
        ),
    ]
