# Generated by Django 6.1.1 on 2026-10-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_callersession_login_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CALLER', 'Caller'), ('IT', 'IT'), ('VIDEO_EDITOR', 'Video Editor'), ('ACCOUNTANT', 'Accountant'), ('EMPLOYEE', 'Employee'), ('COUNSELOR', 'Counselor')], default='CALLER', max_length=30),
        ),
    ]
