# Generated by Django 6.1.1 on 2026-10-08 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_counselor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='callersession',
            name='location_state',
            field=models.CharField(choices=[('UNKNOWN', 'Not reported'), ('ACTIVE', 'Collecting'), ('UNAVAILABLE', 'Location unavailable'), ('STOPPED', 'Stopped')], default='UNKNOWN', max_length=16),
        ),
        migrations.AddField(
            model_name='callersession',
            name='location_state_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeLocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_points', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_points', to='accounts.callersession')),
            ],
            options={
                'ordering': ['recorded_at', 'pk'],
                'indexes': [models.Index(fields=['employee', '-recorded_at', '-id'], name='employee_location_latest')],
                'constraints': [models.UniqueConstraint(fields=('session', 'recorded_at'), name='unique_session_location_time'), models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='employee_latitude_valid'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='employee_longitude_valid'), models.CheckConstraint(condition=models.Q(('accuracy__gte', 0)), name='employee_accuracy_valid')],
            },
        ),
    ]
