# Generated by Django 6.1.1 on 2026-10-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_callersession_location_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callersession',
            name='location_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='employeelocationpoint',
            name='mocked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeelocationpoint',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='employeelocationpoint',
            name='source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
