# Generated by Django 6.1.1 on 2026-09-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_attendancephotochallenge_attendancephotorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancephotorequest',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
