# Generated by Django 6.1.1 on 2026-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
