# Generated by Django 6.1.1 on 2026-09-24 12:25

from django.db import migrations, models


def copy_existing_links(apps, schema_editor):
    Report = apps.get_model('web', 'WorkReport')
    for report in Report.objects.using(schema_editor.connection.alias).exclude(work_link='').iterator():
        report.work_links = [report.work_link]
        report.save(update_fields=['work_links'], using=schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_workreport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='work_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='work_link',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.RunPython(copy_existing_links, migrations.RunPython.noop),
    ]
