# Generated by Django 6.1.1 on 2026-10-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_noticeattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='login_remark',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
