# Generated by Django 6.1.1 on 2026-10-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_attendance_login_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='project_reports',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
