# Generated by Django 6.1.1 on 2026-09-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadassignmenthistory_leadimportbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadimportbatch'),
        ),
    ]
