# Generated by Django 6.1.1 on 2026-09-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_import_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CALLED', 'Called'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('CALL_BACK', 'Call Back'), ('WRONG_NUMBER', 'Wrong Number'), ('FORWARDED_CALLS', 'Forwarded Calls'), ('NO_CANDIDATE', 'No Candidate'), ('DISCONNECTED', 'Disconnected'), ('ADMISSION_DONE', 'Admission Done'), ('ALL_WAITING', 'All Waiting'), ('NOT_REACHABLE', 'Not Reachable'), ('RINGING', 'Ringing')], db_index=True, default='PENDING', max_length=30),
        ),
    ]
