# Generated by Django 6.1.1 on 2026-09-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
