# Generated by Django 6.1.1 on 2026-09-28 05:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_services(apps, schema_editor):
    Service = apps.get_model('leads', 'Service')
    Lead = apps.get_model('leads', 'Lead')
    alias = schema_editor.connection.alias
    services = {code: Service.objects.using(alias).create(name=code, code=code)
                for code in ('MBBS', 'MBA', 'APOSTILLE', 'OTHER')}
    # Preserve the original Phase 1 text and all import/assignment data.
    for lead in Lead.objects.using(alias).exclude(service='').iterator():
        service = services.get(lead.service.strip().upper(), services['OTHER'])
        Lead.objects.using(alias).filter(pk=lead.pk).update(service_type_id=service.pk)
    Lead.objects.using(alias).filter(service='', source='website', import_batch__isnull=True).update(
        service_type_id=services['OTHER'].pk)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z0-9_]*$', 'Use an uppercase service code.')])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.service'),
        ),
        migrations.RunPython(seed_services, migrations.RunPython.noop),
    ]
