# Generated by Django 6.1.1 on 2026-09-28 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_website_lead_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadavailability',
            name='available_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leadavailability',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
