# Generated by Django 6.1.1 on 2026-09-28 06:11

import apps.leads.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_website_retry_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the website or lead source', max_length=150)),
                ('code', models.CharField(db_index=True, help_text="Unique source identifier (e.g. 'website', 'landing_page', 'study_mbbs')", max_length=100, unique=True)),
                ('api_key', models.CharField(db_index=True, default=apps.leads.models.generate_api_key, help_text='API credential / secret key for this website source', max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this website source is currently active and permitted to submit leads')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_services', models.ManyToManyField(blank=True, help_text='Allowed services for this source. If empty, all active services are permitted.', related_name='website_sources', to='leads.service')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteLeadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('is_duplicate', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_submissions', to='leads.lead')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_submissions', to='leads.service')),
                ('website_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='leads.websitesource')),
            ],
            options={
                'ordering': ['-submitted_at', '-pk'],
            },
        ),
    ]
