# Generated by Django 6.1.1 on 2026-09-28 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_websitesource_websiteleadsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesource',
            name='default_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_website_sources', to='leads.service'),
        ),
    ]
