# Generated by Django 6.1.1 on 2026-09-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_websitesource_default_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesource',
            name='allowed_services',
            field=models.ManyToManyField(blank=True, help_text='Allowed services for this source. If empty, no services are permitted.', related_name='website_sources', to='leads.service'),
        ),
    ]
