# Generated by Django 6.1.1 on 2026-09-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_websitesource_allowed_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesource',
            name='allowed_origins',
            field=models.JSONField(blank=True, default=list, help_text='Allowed HTTPS origins for this website source.'),
        ),
    ]
