# Generated by Django 6.1.1 on 2026-09-28 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_websitesource_allowed_origins'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='candidate_type',
            field=models.CharField(choices=[('LEAD', 'Online Lead'), ('WALK_IN', 'Walk-in')], db_index=True, default='LEAD', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='walk_in_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='admission',
            name='walk_in_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='admission',
            name='walk_in_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='admission',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='websitesource',
            name='allowed_origins',
            field=models.JSONField(blank=True, default=list, help_text='Allowed HTTPS origins for this website source.', null=True),
        ),
    ]
