# Generated by Django 6.1.1 on 2026-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_admission_candidate_type_admission_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadavailability',
            name='call_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
