# Generated by Django 6.1.1 on 2026-09-30 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_leadavailability_call_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselling_type', models.CharField(choices=[('WALK_IN', 'Walk-in Counselling'), ('ONLINE', 'Online / Phone Counselling')], db_index=True, default='WALK_IN', max_length=20)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=150)),
                ('conducted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(limit_choices_to={'role': 'CALLER'}, on_delete=django.db.models.deletion.PROTECT, related_name='caller_counsellings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellings_recorded', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counsellings', to='leads.lead')),
            ],
            options={
                'ordering': ['-conducted_at', '-created_at'],
            },
        ),
    ]
