# Generated by Django 6.1.1 on 2026-10-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_seed_whatsapp_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselling',
            name='visitor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='counselling',
            name='visitor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='counselling',
            name='visitor_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='counselling',
            name='counselling_type',
            field=models.CharField(choices=[('WALK_IN', 'Walk-in Counselling'), ('ONLINE', 'Online / Phone Counselling'), ('GOOGLE_MEET', 'Google Meet Counselling')], db_index=True, default='WALK_IN', max_length=20),
        ),
        migrations.AlterField(
            model_name='counselling',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counsellings', to='leads.lead'),
        ),
    ]
