# Generated by Django 6.1.1 on 2026-10-05 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_call_course_classification_and_more'),
        ('leads', '0020_counselling_visitors_and_google_meet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='preferred_course',
            field=models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('BDS', 'BDS'), ('BTECH', 'BTECH'), ('GNM_NURSING', 'GNM NURSING'), ('BSC_NURSING', 'BSC NURSING'), ('PHARMACY', 'PHARMACY'), ('MBA', 'MBA'), ('MD_MS', 'MD/MS'), ('OTHERS', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_course_custom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappactivity',
            name='call',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_activity', to='calls.call'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whatsappactivity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_activities', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
