# Generated by Django 6.1.1 on 2026-10-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_lead_preferred_course_lead_preferred_course_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='candidate_type',
            field=models.CharField(choices=[('LEAD', 'Online Lead'), ('WALK_IN', 'Walk-in'), ('EXTERNAL', 'External Student')], db_index=True, default='LEAD', max_length=20),
        ),
    ]
