# Generated by Django 6.1.1 on 2026-10-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_alter_admission_candidate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselling',
            name='visitor_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CALLED', 'Called'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('CALL_BACK', 'Call Back'), ('WRONG_NUMBER', 'Wrong Number'), ('FORWARDED_CALLS', 'Forwarded Calls'), ('NO_CANDIDATE', 'No Candidate'), ('DISCONNECTED', 'Disconnected'), ('ADMISSION_DONE', 'Admission Done'), ('ALL_WAITING', 'Call Waiting'), ('NOT_REACHABLE', 'Not Reachable'), ('RINGING', 'Ringing'), ('ADMISSION_DONE_BY_OTHER_CONSULTANCY', 'Admission done by other consultancy'), ('B2B', 'B2B')], db_index=True, default='PENDING', max_length=50),
        ),
    ]
