# Generated by Django 6.1.1 on 2026-10-08 07:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_counselling_visitor_source_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apostille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_type', models.CharField(choices=[('EXISTING_LEAD', 'Existing Lead'), ('EXTERNAL', 'External')], default='EXTERNAL', max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('number_of_documents', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('country', models.CharField(max_length=100)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ledger_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(limit_choices_to={'role': 'CALLER'}, on_delete=django.db.models.deletion.PROTECT, related_name='caller_apostilles', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apostilles_recorded', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apostilles', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('number_of_documents__gte', 1)), name='apostille_positive_documents'), models.CheckConstraint(condition=models.Q(('amount_received__gte', 0)), name='apostille_nonnegative_amount'), models.CheckConstraint(condition=models.Q(('country', ''), _negated=True), name='apostille_country_required'), models.CheckConstraint(condition=models.Q(models.Q(('candidate_type', 'EXTERNAL'), ('lead__isnull', True), models.Q(('name', ''), _negated=True), models.Q(('phone', ''), _negated=True)), models.Q(('candidate_type', 'EXISTING_LEAD'), ('lead__isnull', False), ('name', ''), ('phone', '')), _connector='OR'), name='apostille_candidate_consistent')],
            },
        ),
    ]
