# Generated by Django 6.1.1 on 2026-10-08 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_alter_call_outcome'),
        ('leads', '0024_apostille'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCounselorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('forwarded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, choices=[('REASSIGNED', 'Reassigned to another counselor')], max_length=20)),
                ('caller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_forwarded_leads', to=settings.AUTH_USER_MODEL)),
                ('counselor', models.ForeignKey(limit_choices_to={'role': 'COUNSELOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='counselor_assignments', to=settings.AUTH_USER_MODEL)),
                ('forwarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_forwards', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_assignments', to='leads.lead')),
                ('source_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselor_assignments', to='calls.call')),
            ],
            options={
                'ordering': ['-forwarded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CounselorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CALL', 'Counselor call'), ('NOTE', 'Note')], default='NOTE', max_length=10)),
                ('body', models.TextField(max_length=4000)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('client_event_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counselor_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_notes', to='leads.lead')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='leads.leadcounselorassignment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_requests', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requests', to='leads.lead')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admission_requests', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_requests', to='leads.leadcounselorassignment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='leadcounselorassignment',
            index=models.Index(fields=['counselor', 'is_active'], name='counselor_assignment_active'),
        ),
        migrations.AddConstraint(
            model_name='leadcounselorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('lead',), name='one_active_counselor_per_lead'),
        ),
        migrations.AddConstraint(
            model_name='counselornote',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('counselor', 'client_event_id'), name='unique_counselor_note_client_event'),
        ),
        migrations.AddConstraint(
            model_name='admissionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('lead',), name='one_pending_admission_request_per_lead'),
        ),
    ]
