# Generated by Django 6.1.1 on 2026-10-10 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_counselor_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CALLED', 'Called'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('CALL_BACK', 'Call Back'), ('WRONG_NUMBER', 'Wrong Number'), ('FORWARDED_CALLS', 'Forwarded Calls'), ('NO_CANDIDATE', 'No Candidate'), ('DISCONNECTED', 'Disconnected'), ('ADMISSION_DONE', 'Admission Done'), ('ALL_WAITING', 'Call Waiting'), ('NOT_REACHABLE', 'Not Reachable'), ('RINGING', 'Ringing'), ('ADMISSION_DONE_BY_OTHER_CONSULTANCY', 'Admission done by other consultancy'), ('B2B', 'B2B'), ('CONVERTED', 'Converted'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required')], db_index=True, default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='ApostilleLeadDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=200)),
                ('number_of_documents', models.PositiveIntegerField()),
                ('conversion', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('client_event_id', models.UUIDField(unique=True)),
                ('submission_fingerprint', models.CharField(editable=False, max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apostille_details', to='leads.lead')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('number_of_documents__gte', 1)), name='apostille_lead_positive_docs'), models.CheckConstraint(condition=models.Q(models.Q(('conversion', True), ('reason', '')), models.Q(('conversion', False), ('notes', ''), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='apostille_lead_conversion_fields')],
            },
        ),
    ]
