# Generated by Django 6.1.1 on 2026-09-21 06:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('followups', '0002_rename_note_followup_notes_and_more'),
        ('leads', '0003_lead_import_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('COUNSELLING', 'Counselling / demo scheduled'), ('APPLICATION', 'Application started'), ('ADMISSION', 'Verified admission'), ('FALSE_STATUS', 'False / incorrect status')], max_length=24)),
                ('reason', models.TextField(help_text='Evidence or reference for this milestone / status review.')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_milestones', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_milestones', to='leads.lead')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['caller', 'occurred_at'], name='performance_caller__7dfa87_idx')],
                'constraints': [models.UniqueConstraint(fields=('lead', 'event'), name='one_lead_milestone'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='milestone_reason_required')],
            },
        ),
        migrations.CreateModel(
            name='PointsAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_points_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='adjustment_reason_required'), models.CheckConstraint(condition=models.Q(('points', 0), _negated=True), name='adjustment_nonzero')],
            },
        ),
        migrations.CreateModel(
            name='PointsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('DIALED', 'Dialed'), ('CONNECTED', 'Connected'), ('DURATION', 'Talk-time bonus'), ('FOLLOWUP_COMPLETED', 'Follow-up completed'), ('INTERESTED', 'Interested lead'), ('COUNSELLING', 'Counselling / demo scheduled'), ('APPLICATION', 'Application started'), ('ADMISSION', 'Verified admission'), ('INVALID', 'Invalid number'), ('MISSED_FOLLOWUP', 'Missed follow-up'), ('FALSE_STATUS', 'False / incorrect status'), ('MANUAL', 'Manual adjustment')], max_length=24)),
                ('points', models.IntegerField()),
                ('reason', models.TextField()),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='calls.call')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_entries', to=settings.AUTH_USER_MODEL)),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='followups.followup')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='leads.lead')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
                'permissions': [('manage_points', 'Manage caller points and verified milestones')],
                'indexes': [models.Index(fields=['caller', 'occurred_at'], name='performance_caller__bc247e_idx'), models.Index(fields=['event', 'occurred_at'], name='performance_event_d02997_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='points_reason_required')],
            },
        ),
    ]
