# Generated by Django 6.1.1 on 2026-10-01 05:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_counselling'),
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointsadjustment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pointsadjustment',
            name='reason_type',
            field=models.CharField(choices=[('UNPLANNED_LEAVE', 'Unplanned leave (-50)'), ('MORE_THAN_ONE_CONSECUTIVE_HOLIDAY', 'More than one consecutive holiday (-2 per holiday)'), ('MORE_THAN_THREE_HOLIDAYS_IN_MONTH', 'More than three holidays in month (-2 per additional holiday)'), ('INDISCIPLINE_WORKPLACE_CONDUCT', 'Indiscipline / workplace conduct (-5 per incident)'), ('OTHER', 'Other (custom reason & points)')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='pointsentry',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='leads.admission'),
        ),
        migrations.AddField(
            model_name='pointsentry',
            name='counselling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='leads.counselling'),
        ),
        migrations.AlterField(
            model_name='leadmilestone',
            name='event',
            field=models.CharField(choices=[('COUNSELLING_COMPLETED', 'Counselling / demo completed'), ('VERIFIED_ADMISSION', 'Verified admission'), ('COUNSELLING', 'Counselling / demo scheduled'), ('APPLICATION', 'Application started'), ('ADMISSION', 'Verified admission'), ('FALSE_STATUS', 'False / incorrect status')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pointsadjustment',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_points_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointsadjustment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_points_adjustments_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointsentry',
            name='event',
            field=models.CharField(choices=[('CALL_DAILY_BONUS', 'Daily call bonus'), ('INTERESTED_LEAD', 'Interested lead'), ('COUNSELLING_COMPLETED', 'Counselling / demo completed'), ('VERIFIED_ADMISSION', 'Verified admission'), ('MISSED_FOLLOWUP', 'Missed follow-up'), ('ADMIN_ADJUSTMENT', 'Admin adjustment'), ('DIALED', 'Dialed'), ('CONNECTED', 'Connected'), ('DURATION', 'Talk-time bonus'), ('FOLLOWUP_COMPLETED', 'Follow-up completed'), ('INTERESTED', 'Interested lead'), ('COUNSELLING', 'Counselling / demo scheduled'), ('APPLICATION', 'Application started'), ('ADMISSION', 'Verified admission'), ('INVALID', 'Invalid number'), ('FALSE_STATUS', 'False / incorrect status'), ('MANUAL', 'Manual adjustment')], max_length=32),
        ),
        migrations.CreateModel(
            name='PeerAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, help_text='Review month in YYYY-MM format', max_length=7)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_peer_appreciations', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_peer_appreciations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'employee', 'month'), name='unique_peer_appreciation_reviewer_employee_month'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 10)), name='peer_score_between_1_and_10'), models.CheckConstraint(condition=models.Q(('reviewer', models.F('employee')), _negated=True), name='peer_no_self_rating')],
            },
        ),
    ]
