# Generated by Django 6.1.1 on 2026-10-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_alter_pointsadjustment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsentry',
            name='rules_version',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pointsadjustment',
            name='reason_type',
            field=models.CharField(choices=[('UNPLANNED_LEAVE', 'Unplanned leave (-100 per day)'), ('MORE_THAN_ONE_CONSECUTIVE_HOLIDAY', 'More than one consecutive holiday (-2 per holiday)'), ('MORE_THAN_THREE_HOLIDAYS_IN_MONTH', 'More than three holidays in month (-2 per additional holiday)'), ('INDISCIPLINE_WORKPLACE_CONDUCT', 'Code of conduct / CRM misreporting (-50 per incident)'), ('CONSECUTIVE_UNAPPROVED_LEAVE', 'Consecutive unapproved leave (>2 days, -50 per day)'), ('MANAGEMENT_BONUS', 'Management spot / Expo bonus (+50 to +200)'), ('OTHER', 'Other (custom reason & points)')], default='OTHER', max_length=50),
        ),
    ]
