# Generated by Django 6.1.1 on 2026-10-08 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_apostille'),
        ('performance', '0003_pointsentry_rules_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsentry',
            name='apostille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_entries', to='leads.apostille'),
        ),
        migrations.AlterField(
            model_name='pointsentry',
            name='event',
            field=models.CharField(choices=[('CALL_DAILY_BONUS', 'Daily call bonus'), ('INTERESTED_LEAD', 'Interested lead'), ('COUNSELLING_COMPLETED', 'Counselling / demo completed'), ('VERIFIED_ADMISSION', 'Verified admission'), ('APOSTILLE', 'Apostille'), ('MISSED_FOLLOWUP', 'Missed follow-up'), ('ADMIN_ADJUSTMENT', 'Admin adjustment'), ('DIALED', 'Dialed'), ('CONNECTED', 'Connected'), ('DURATION', 'Talk-time bonus'), ('FOLLOWUP_COMPLETED', 'Follow-up completed'), ('INTERESTED', 'Interested lead'), ('COUNSELLING', 'Counselling / demo scheduled'), ('APPLICATION', 'Application started'), ('ADMISSION', 'Verified admission'), ('INVALID', 'Invalid number'), ('FALSE_STATUS', 'False / incorrect status'), ('MANUAL', 'Manual adjustment')], max_length=32),
        ),
    ]
