# Generated by Django 6.1.1 on 2026-09-10 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='followup',
            name='caller',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CALLER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to=settings.AUTH_USER_MODEL),
        ),
    ]
