# Generated by Django 6.1.1 on 2026-09-21 06:53

from django.db import migrations, models


def preserve_completion_times(apps, schema_editor):
    FollowUp = apps.get_model('followups', 'FollowUp')
    FollowUp.objects.using(schema_editor.connection.alias).filter(status='COMPLETED').update(completed_at=models.F('updated_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0002_rename_note_followup_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(preserve_completion_times, migrations.RunPython.noop),
    ]
