# Generated by Django 6.1.1 on 2026-09-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_call_phone_number_call_submission_fingerprint_and_more'),
        ('followups', '0003_followup_completed_at'),
        ('leads', '0006_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='call',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup', to='calls.call'),
        ),
        migrations.AddField(
            model_name='followup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='followup',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead'),
        ),
    ]
