# Generated by Django 6.1.1 on 2026-10-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0004_followup_call_followup_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
