# Generated by Django 6.1.1 on 2026-09-10 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(blank=True, choices=[('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('CALL_BACK', 'Call Back'), ('WRONG_NUMBER', 'Wrong Number')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(limit_choices_to={'role': 'CALLER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls_made', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead')),
            ],
        ),
    ]
