# Generated by Django 6.1.1 on 2026-09-21 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
        ('leads', '0003_lead_import_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='client_event_id',
            field=models.UUIDField(blank=True, help_text='Optional idempotency key supplied by the caller app.', null=True),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['caller', 'started_at'], name='calls_call_caller__6f7af3_idx'),
        ),
        migrations.AddConstraint(
            model_name='call',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('caller', 'client_event_id'), name='unique_caller_call_event'),
        ),
    ]
