# Generated by Django 6.1.1 on 2026-09-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_alter_call_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='outcome',
            field=models.CharField(blank=True, choices=[('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('CALL_BACK', 'Call Back'), ('WRONG_NUMBER', 'Wrong Number'), ('FORWARDED_CALLS', 'Forwarded Calls'), ('NO_CANDIDATE', 'No Candidate'), ('DISCONNECTED', 'Disconnected'), ('ADMISSION_DONE', 'Admission Done'), ('ALL_WAITING', 'Call Waiting'), ('NOT_REACHABLE', 'Not Reachable'), ('RINGING', 'Ringing')], max_length=30),
        ),
    ]
