# Generated by Django 6.1.1 on 2026-09-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_alter_call_outcome'),
        ('leads', '0006_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='call',
            name='submission_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='call',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead'),
        ),
    ]
