# Generated by Django 6.1.1 on 2026-09-24 05:25

import apps.calls.recording_storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_call_phone_number_call_submission_fingerprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=apps.calls.recording_storage.recording_storage, upload_to='call-recordings/%Y/%m/%d/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='calls.call')),
            ],
        ),
    ]
