# Generated by Django 6.1.1 on 2026-10-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_callrecording'),
        ('leads', '0020_counselling_visitors_and_google_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='course_classification',
            field=models.CharField(blank=True, choices=[('OWN', 'Own course'), ('OTHER', 'Other course'), ('UNKNOWN', 'Unknown preferred course')], editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='call',
            name='expected_admission_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='selected_course',
            field=models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('BDS', 'BDS'), ('BTECH', 'BTECH'), ('GNM_NURSING', 'GNM NURSING'), ('BSC_NURSING', 'BSC NURSING'), ('PHARMACY', 'PHARMACY'), ('MBA', 'MBA'), ('MD_MS', 'MD/MS'), ('OTHERS', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='selected_course_custom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='call',
            name='whatsapp_message',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='call',
            name='whatsapp_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_calls', to='leads.whatsapptemplate'),
        ),
    ]
