# Generated by Django 6.1.1 on 2026-10-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0008_alter_call_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='outcome',
            field=models.CharField(blank=True, choices=[('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('CALL_BACK', 'Call Back'), ('WRONG_NUMBER', 'Wrong Number'), ('FORWARDED_CALLS', 'Forwarded Calls'), ('NO_CANDIDATE', 'No Candidate'), ('DISCONNECTED', 'Disconnected'), ('ADMISSION_DONE', 'Admission Done'), ('ALL_WAITING', 'Call Waiting'), ('NOT_REACHABLE', 'Not Reachable'), ('RINGING', 'Ringing'), ('ADMISSION_DONE_BY_OTHER_CONSULTANCY', 'Admission done by other consultancy'), ('B2B', 'B2B'), ('CONVERTED', 'Converted'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required')], max_length=50),
        ),
    ]
