# Generated by Django 6.1.1 on 2026-10-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LEAD_ASSIGNED', 'Lead assigned'), ('TEAM_CHAT', 'Team chat message'), ('NOTICE', 'Notice published')], max_length=40),
        ),
    ]
