# Generated by Django 6.1.1 on 2026-10-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_team_chat_and_notice_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LEAD_ASSIGNED', 'Lead assigned'), ('TEAM_CHAT', 'Team chat message'), ('NOTICE', 'Notice published'), ('FOLLOWUP_DUE', 'Follow-up due')], max_length=40),
        ),
    ]
