# Generated by Django 6.1.1 on 2026-10-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LEAD_ASSIGNED', 'Lead assigned'), ('TEAM_CHAT', 'Team chat message'), ('NOTICE', 'Notice published'), ('FOLLOWUP_DUE', 'Follow-up due'), ('COUNSELOR_LEAD_FORWARDED', 'Lead forwarded to counselor'), ('ADMISSION_REQUESTED', 'Admission requested')], max_length=40),
        ),
    ]
