# Generated by Django 6.1.1 on 2026-09-15 10:08

from django.db import migrations


def create_general_channel(apps, schema_editor):
    ChatChannel = apps.get_model('chat', 'ChatChannel')
    ChatChannel.objects.get_or_create(
        name='General',
        defaults={'kind': 'GENERAL', 'description': 'Company-wide chat — every employee is a member automatically.'},
    )


def remove_general_channel(apps, schema_editor):
    ChatChannel = apps.get_model('chat', 'ChatChannel')
    ChatChannel.objects.filter(name='General', kind='GENERAL').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_general_channel, remove_general_channel),
    ]
